vich_uploader:
    db_driver: orm

    mappings:
        album_image:
            uri_prefix: /media/images
            upload_destination: '%kernel.project_dir%/public/media/images'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

        projet_image:
            uri_prefix: /media/projets
            upload_destination: '%kernel.project_dir%/public/media/projets'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer

                # options: { property: 'slugImage'}
            # directory_namer: services.directory_namer
#            uri_prefix: /media/images
#            upload_destination: '%kernel.project_dir%/public/media/images'

    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
